### ISSUE TITLE
Passwordless Frontend Login (YCom)

### ISSUE THREAD

**Issue by alxndr-w** [eaCe/passwordless_login#1]
Es wäre genial, wenn das Addon optional einen passwortlosen YCom-Login durchführen könnte.

**Comment by eaCe** [comment]
Wie würde ich diesen vom REDAXO-Login unterscheiden können?

**Comment by alxndr-w** [comment]
Du kannst prüfen, ob man sich auf der in YCom eingerichteten Login-Seite befindet. Du könntest die Klasse der Login-Action von YCom dafür erweitern.

**Comment by alxndr-w** [comment]
Das Formular könnte überall auftauchen, aber intern geroutet wird das schon über die Login-Seite.

**Comment by eaCe** [comment]
Ok das wusste ich nicht. Dennoch wäre es nicht der falsche Ort? Der Login käme erst später. Initial geht es um den Versand der Mail. Ich kann es auch mit dem Login probieren. Beim ersten überfliegen weiß ich allerdings noch nicht wie ich mich da rein hooken sollte ohne die Login-Funktion zu großen Teilen nach- bzw. umzubauen.

**Comment by eaCe** [comment]
Ich bin mir immer noch nicht sicher wie ich das am schönsten angehen soll. Ich werde die kommenden Tage mal testen...

**Comment by alxndr-w** [comment]
@tyrant88 wie hast du das nun eigentlich in unserem Projekt gelöst?

**Comment by tyrant88** [comment]
gelöst? Ich weiß nicht worum es hier geht. 
Im Projekt nutzen wir ycom_auth_login um sich mit einem URL-Parameter einzuloggen.

**Comment by alxndr-w** [comment]
Das ist prinzipiell inzwischen mit YCom-Bordmitteln möglich und wurde rudimentär dokumentiert.

**Comment by eaCe** [comment]
Danke für den Hinweis
